const apartments = [
    {
        sale: '',
        offer: '',
        star: 'img/star_1.png',
        name: 'Студия №44',
        look: 'без отделки',
        square: 28,
        floor: '12/14',
        price: 1900000,
        img: 'img/apartments/1.png',
        rooms: 0,
        mark: 'busy',
        status: 'Забронировано'
    },
    {
        sale: '',
        offer: '',
        star: 'img/star_2.png',
        name: 'Однокомнатная №666',
        look: 'базовая отделка',
        square: 66,
        floor: '6/6',
        price: 1666666,
        img: 'img/apartments/2.png',
        rooms: 1,
        mark: 'free',
        status: 'Свободно'
    },
    {
        sale: '',
        offer: '',
        star: 'img/star_1.png',
        name: 'Двухкомнатная №567',
        look: 'черновая отделка',
        square: 65.6,
        floor: '7/14',
        price: 5900000,
        img: 'img/apartments/3.png',
        rooms: 2,
        mark: 'sold',
        status: 'Продано'
    },
    {
        sale: '',
        offer: '',
        star: 'img/star_2.png',
        name: 'Трехкомнатная №45',
        look: 'без отделки',
        square: 56,
        floor: '1/14',
        price: 12900000,
        img: 'img/apartments/4.png',
        rooms: 3,
        mark: 'booked',
        status: 'Забронировано'
    },
    {
        sale: '-17%',
        offer: 'Шок цена',
        star: 'img/star_1.png',
        name: 'Студия  №25',
        look: 'черновая отделка',
        square: 18,
        floor: '12/14',
        price: 1900000,
        img: 'img/apartments/5.png',
        rooms: 0,
        mark: 'booked',
        status: 'Забронировано'
    },
    {
        sale: '-6%',
        offer: '',
        star: 'img/star_2.png',
        name: 'Четырехкомнатная №259',
        look: 'черновая отделка',
        square: 98,
        floor: '14/14',
        price: 23900000,
        img: 'img/apartments/6.png',
        rooms: 4,
        mark: 'booked',
        status: 'Забронировано'
    },
    {
        sale: '',
        offer: '',
        star: 'img/star_2.png',
        name: 'Однокомнатная №56',
        look: 'без отделки',
        square: 36,
        floor: '3/6',
        price: 5666666,
        img: 'img/apartments/7.png',
        rooms: 1,
        mark: 'free',
        status: 'Свободно'
    },
    {
        sale: '',
        offer: '',
        star: 'img/star_2.png',
        name: 'Трехкомнтаная №46',
        look: 'черновая отделка',
        square: 86,
        floor: '1/6',
        price: 5696664,
        img: 'img/apartments/8.png',
        rooms: 3,
        mark: 'free',
        status: 'Свободно'
    },
    {
        sale: '-9%',
        offer: 'Шок цена',
        star: 'img/star_2.png',
        name: 'Однокомнатная №2',
        look: 'черновая отделка',
        square: 18,
        floor: '3/14',
        price: 1200000,
        img: 'img/apartments/9.png',
        rooms: 1,
        mark: 'booked',
        status: 'Забронировано'
    },
    {
        sale: '-6%',
        offer: '',
        star: 'img/star_2.png',
        name: 'Студия №12',
        look: 'черновая отделка',
        square: 38,
        floor: '6/14',
        price: 1500500,
        img: 'img/apartments/10.png',
        rooms: 0,
        mark: 'booked',
        status: 'Забронировано'
    },
    {
        sale: '-6%',
        offer: '',
        star: 'img/star_2.png',
        name: 'Однокомнатная №8',
        look: 'черновая отделка',
        square: 48,
        floor: '3/14',
        price: 6200000,
        img: 'img/apartments/11.png',
        rooms: 1,
        mark: 'booked',
        status: 'Забронировано'
    },
    {
        sale: '-6%',
        offer: '',
        star: 'img/star_2.png',
        name: 'Двухкомнатная №23',
        look: 'базовая отделка',
        square: 48,
        floor: '3/14',
        price: 5255006,
        img: 'img/apartments/12.png',
        rooms: 2,
        mark: 'booked',
        status: 'Забронировано'
    }
]